#!/usr/bin/env bash
# Displays 'To infinity and beyond' indefinitely
# With a sleep 2 in between each iteration
# And i am invincible SIGTERM

trap 'echo "I am invincible!!!"' SIGTERM
while true
do
    echo "To infinity and beyond"
    sleep 2
done
